// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_Qlrgakad_AJlLKuiiD5tL1bygtKkvDQ',
    appId: '1:615679628203:web:b6ac550ff4fc27a04a78ee',
    messagingSenderId: '615679628203',
    projectId: 'imager-581cd',
    authDomain: 'imager-581cd.firebaseapp.com',
    storageBucket: 'imager-581cd.appspot.com',
    measurementId: 'G-NJXB6R104X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcA_7XSBMjj3OTGOcnhjnLthJxmUWQ1j4',
    appId: '1:615679628203:android:aad698362d11671d4a78ee',
    messagingSenderId: '615679628203',
    projectId: 'imager-581cd',
    storageBucket: 'imager-581cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8Glp_vBjMUy3yYmEdvKCPrc9iVNIdQkA',
    appId: '1:615679628203:ios:f568a8c986d05c3f4a78ee',
    messagingSenderId: '615679628203',
    projectId: 'imager-581cd',
    storageBucket: 'imager-581cd.appspot.com',
    iosClientId: '615679628203-grrrcga1fo416atcd325vdg62ip31ne6.apps.googleusercontent.com',
    iosBundleId: 'com.example.imager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8Glp_vBjMUy3yYmEdvKCPrc9iVNIdQkA',
    appId: '1:615679628203:ios:f568a8c986d05c3f4a78ee',
    messagingSenderId: '615679628203',
    projectId: 'imager-581cd',
    storageBucket: 'imager-581cd.appspot.com',
    iosClientId: '615679628203-grrrcga1fo416atcd325vdg62ip31ne6.apps.googleusercontent.com',
    iosBundleId: 'com.example.imager',
  );
}
